;----------------------------------------------------------------
; inc/defines/housetypes.inc
;
; HouseType Definitions
;   HouseType represents a house supported by the game
;
;----------------------------------------------------------------

%ifndef DEFINE_HOUSETYPES
%define DEFINE_HOUSETYPES 

; HouseType
%assign HouseType.Spain                    0
%assign HouseType.Greece                   1
%assign HouseType.USSR                     2
%assign HouseType.England                  3
%assign HouseType.Ukraine                  4
%assign HouseType.Germany                  5
%assign HouseType.France                   6
%assign HouseType.Turkey                   7
%assign HouseType.GoodGuy                  8
%assign HouseType.BadGuy                   9
%assign HouseType.Neutral                  10
%assign HouseType.Special                  11
%assign HouseType.Multi1                   12
%assign HouseType.Multi2                   13
%assign HouseType.Multi3                   14
%assign HouseType.Multi4                   15
%assign HouseType.Multi5                   16
%assign HouseType.Multi6                   17
%assign HouseType.Multi7                   18
%assign HouseType.Multi8                   19

;new Houses
%assign HouseType.Multi9                   20
%assign HouseType.Multi10                  21
%assign HouseType.Multi11                  22
%assign HouseType.Multi12                  23
%assign HouseType.Multi13                  24
%assign HouseType.Multi14                  25
%assign HouseType.Multi15                  26
%assign HouseType.Multi16                  27
%assign HouseType.Multi17                  28
%assign HouseType.Multi18                  29
%assign HouseType.Multi19                  30
%assign HouseType.Multi20                  31

%endif

