;----------------------------------------------------------------
; inc/defines/missiontypes.inc
;
; MissionType Definitions
;   Per description from Remastered source: 
;   Types of games; used to tell which protocol we're using
;
;----------------------------------------------------------------

; MissionType
%assign MissionType.MISSION_NONE             -1 
%assign MissionType.MISSION_SLEEP            0  
%assign MissionType.MISSION_ATTACK           1  
%assign MissionType.MISSION_MOVE             2 
%assign MissionType.MISSION_QMOVE            3  
%assign MissionType.MISSION_RETREAT          4  
%assign MissionType.MISSION_GUARD            5  
%assign MissionType.MISSION_STICKY           6  
%assign MissionType.MISSION_ENTER            7  
%assign MissionType.MISSION_CAPTURE          8  
%assign MissionType.MISSION_HARVEST          9  
%assign MissionType.MISSION_GUARD_AREA       10  
%assign MissionType.MISSION_RETURN           11  
%assign MissionType.MISSION_STOP             12
%assign MissionType.MISSION_AMBUSH           13  
%assign MissionType.MISSION_HUNT             14
%assign MissionType.MISSION_UNLOAD           15  
%assign MissionType.MISSION_SABOTAGE         16  
%assign MissionType.MISSION_CONSTRUCTION     17  
%assign MissionType.MISSION_DECONSTRUCTION   18  
%assign MissionType.MISSION_REPAIR           19  
%assign MissionType.MISSION_RESCUE           20  
%assign MissionType.MISSION_MISSILE          21  
%assign MissionType.MISSION_HARMLESS         22


