;----------------------------------------------------------------
; inc/types/FlyClass.inc
;
; Macros to access FlyClass offsets
;
;----------------------------------------------------------------

%ifndef TYPES_FLYCLASS
%define TYPES_FLYCLASS

; TO-DO: confirm the offsets

; define object type field definitions
%define FlyClass.Offset.SpeedAccum                0x0B1    ; byte
%define FlyClass.Offset.SpeedAdd                  0x0B2    ; byte
; 0x0B3

%endif
