;----------------------------------------------------------------
; inc/types/RadioClass.inc
;
; Macros to access RadioClass offsets
;
;----------------------------------------------------------------

%ifndef TYPES_RADIOCLASS
%define TYPES_RADIOCLASS

; define object type field definitions
%define RadioClass.Offset.Old                       0x037    ; 3 byte
%define RadioClass.Offset.Radio                     0x03A    ; ptr
;%define RadioClass.Offset.Messages                      ; 34 bytes (in static)
; 0x03E

%endif
